#设置consul客户端的启动端口号
server:
  port: 9900
#不添加就是unknown作为服务名,需要注意的是在新版本的eureka中是允许出现下划线的，但这在以前是不被允许的，此外此命名规则是忽略大小写的大写
spring:
  application:
    name: "SpringConfigServerApplication"
  cloud:
    consul:
      host: "localhost"
      port: 8500
      discovery:
        service-name: "SpringConfigServerApplication" #向consul进行注册的服务名
        register-health-check: true #健康检查默认为true，不推荐生产环境添加
    config:
      server:
        git:
          uri: "https://gitee.com/anderGitee/single-cen-spring-config-server.git"
          default-label: master
          username: "andergitee"
          password: "adongADONG00"
  rabbitmq:
    host: 192.168.32.128 #你主机的IP地址
    port: 5672 #端口号
    username: singlecen
    password: singlecen
    virtual-host: / #虚拟机名
management:
  endpoints:
    web:
      exposure:
        include: "*" #开启暴露的端点,用于通过url查看json格式的服务端信息。注意:必须加双引号