#设置consul客户端的启动端口号
server:
  port: 9702
#不添加就是unknown作为服务名,需要注意的是在新版本的eureka中是允许出现下划线的，但这在以前是不被允许的，此外此命名规则是忽略大小写的大写
spring:
  application:
    name: "HystrixClientApplication"
  cloud:
    consul:
      host: "localhost"
      port: 8500
      discovery:
        service-name: "HystrixClientApplication" #向consul进行注册的服务名
        register-health-check: true #健康检查默认为true，不推荐生产环境添加
  main:
    allow-bean-definition-overriding: true #开启bean定义时重写机制可以有效避免因为单例模式而造成的bean注入失败
feign:
  httpclient:
    connection-timeout: 1000 #设置超时时间 在老版本中是可以通过设置线程睡眠来触发超时异常，但在新版本中是不行的
  client:
    config:
      CategoryApplication: #默认default
        connection-timeout: 3000 #设置连接超时时间
        read-timeout: 3000 #设置读取超时时间
      default:
        logger-level: "full" #设置日志等级
logging:
  level:
    org:
      scCloud:
        feignclient: debug #单单修改了改部分也不一定有用，必须设置日志等级
hystrix:
  metrics:
    enabled: true #2020.0.X版本以上将 feign.hystrix.enabled=true 变成了左边的方式