#设置nacos客户端的启动端口号
server:
  port: 11000
#服务名称
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 #nocas注册服务地址是来自于${spring.cloud.nacos.server-addr}中的信息
        username: nacos
        password: nacos
        service: ${spring.application.name}
      server-addr: 127.0.0.1:8848 #nocas总的地址信息(默认就是这里写的样子)
  application:
    name: "NacosClient"
