#设置consul客户端的启动端口号
server:
  port: 9601
#不添加就是unknown作为服务名,需要注意的是在新版本的eureka中是允许出现下划线的，但这在以前是不被允许的，此外此命名规则是忽略大小写的大写
spring:
  application:
    name: "Single_Cen_Consul_Client"
  cloud:
    consul:
      host: "localhost"
      port: 8500
      discovery:
        service-name: "${spring.application.name}"
        register-health-check: true #健康检查默认为true，不推荐生产环境添加
#向consul进行注册